[project]
name = "feature-engineering-and-selection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pravin Kalse", email = "48201480+kalsep@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
feature-engineering-and-selection = "feature_engineering_and_selection:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
